const traducao = {
  pt: {
    menu_hamburger: "Menu",
    conectar_walletconnect: "Conectar via WalletConnect",
    cancelar: "Cancelar",
    total_valor: "Valor Total",
    endereco_carteira: "Endereço da Carteira",
    copiar_endereco: "Copiar Endereço",
    copiar_frase: "Copiar frases",
    copiar_chave: "Copiar chave",
    bem_vindo: "Bem-vindo",
    descricao_wallet: "Guarde, envie, compre e venda tokens BSC de forma descentralizada e segura.",
    criar_wallet: "Criar Wallet",
    importar_wallet: "Importar Wallet",
    presale_qualiprevendaA: "Pré-venda Quali",
    menu_tokens: "Menu de Tokens",
    open_nfts: "Galeria de NFTs",
    pix: "Pix",
    error_title: "Erro",
    error_no_wallet: "Nenhuma wallet encontrada.",
    enter_current_password: "Digite sua senha atual",
    show_button: "Mostrar",
    private_key_title: "Chave Privada",
    private_key_copied: "Chave privada copiada!",
    private_key_warning: "Guarde sua chave privada em um local seguro! Se perdê-la, você NÃO conseguirá recuperar sua carteira caso tenha perdido a senha, e todo seu saldo se tornará inacessível. A equipe não poderá ajudá-lo, pois a Wallet é descentralizada.",
    ok_button: "OK",
    hold_button: "mantenha pressionado",
    incorrect_password: "Senha incorreta.",
    confirm_button: "Confirmar",
    new_password_title: "Nova Senha",
    new_password_description: "Digite uma nova senha segura",
    new_password_placeholder: "Nova senha",
    confirm_new_password_placeholder: "Confirme a nova senha",
    new_password_criteria: "A senha deve ter pelo menos 11 caracteres, letras maiúsculas, minúsculas, números e caracteres especiais (!@#$%^&*).",
    change_button: "Alterar",
    validation_fill_both: "Preencha ambos os campos.",
    validation_criteria: "A senha não atende aos critérios mínimos.",
    validation_mismatch: "As senhas não coincidem.",
    success_title: "Sucesso",
    success_password_changed: "Senha alterada com sucesso!",
    reset_password_title: "Resetar Senha",
    paste_private_key: "Cole sua Chave Privada",
    continue_button: "Continuar",
    error_invalid_private_key: "Chave privada inválida.",
    error_private_key_mismatch: "A chave privada não corresponde à wallet atual.",
    define_new_password: "Definir Nova Senha",
    reset_button: "Resetar",
    success_password_reset: "Senha resetada com sucesso!",
    create_wallet_description: "Crie uma senha forte para proteger sua wallet",
    enter_password: "Digite sua senha",
    confirm_password: "Confirme sua senha",
    password_criteria_hint: "A senha deve ter pelo menos 11 caracteres, incluindo letras maiúsculas, minúsculas, números e caracteres especiais (!@#$%^&*).",
    wallet_created: "Wallet Criada",
    wallet_address_label: "Endereço",
    error_create_wallet: "Falha ao criar wallet",
    enter_private_key: "Digite sua chave privada",
    import_button: "Importar",
    validation_empty_private_key: "A chave privada não pode estar vazia!",
    define_secure_password: "Definir Senha Segura",
    encrypt_button: "Criptografar",
    wallet_imported: "Wallet Importada",
    wallet_imported_message: "Endereço:",
    attention_title: "⚠️ ATENÇÃO",
    reset_warning: "Se você não salvou sua chave privada, PERDERÁ TODO O ACESSO à sua wallet!",
    reset_instruction: "Antes de resetar, verifique se salvou sua chave privada para poder recuperar a wallet no futuro.",
    hold_instruction: "Pressione e segure o botão abaixo para resetar.",
    hold_button_text: "Pressione e Segure",
    wallet_reset_title: "Wallet Resetada!",
    wallet_reset_text: "Todos os dados foram apagados. Recarregando...",
    cancel_button: "Cancelar",
    save_your_private_key: "SALVE SUA CHAVE PRIVADA",
    private_key_alert_before_funding: "Antes de adicionar fundos na wallet, salve sua chave privada."
  },
  en: {
    menu_hamburger: "Menu",
    conectar_walletconnect: "Connect via WalletConnect",
    cancelar: "Cancel",
    total_valor: "Total Value",
    endereco_carteira: "Wallet Address",
    copiar_endereco: "Copy Address",
    copiar_frase: "Copy phrase",
    copiar_chave: "Copy key",
    bem_vindo: "Welcome",
    descricao_wallet: "Store, send, buy, and sell tokens BSC in a decentralized and secure way.",
    criar_wallet: "Create Wallet",
    importar_wallet: "Import Wallet",
    menu_tokens: "Tokens Menu",
    open_nfts: "NFT Gallery",
    pix: "Pix",
    error_title: "Error",
    error_no_wallet: "No wallet found.",
    enter_current_password: "Enter your current password",
    show_button: "Show",
    private_key_title: "Private Key",
    private_key_copied: "Private key copied!",
    private_key_warning: "Keep your private key in a safe place! If you lose it, YOU WILL NOT be able to recover your wallet if you lose your password, and all your funds will become inaccessible. The team cannot help, because the wallet is decentralized.",
    ok_button: "OK",
    hold_button: "keep pressed",
    incorrect_password: "Incorrect password.",
    confirm_button: "Confirm",
    new_password_title: "New Password",
    new_password_description: "Enter a secure new password",
    new_password_placeholder: "New password",
    confirm_new_password_placeholder: "Confirm new password",
    new_password_criteria: "Password must be at least 11 characters and include uppercase, lowercase, numbers and special characters (!@#$%^&*).",
    change_button: "Change",
    validation_fill_both: "Fill in both fields.",
    validation_criteria: "Password does not meet the minimum criteria.",
    validation_mismatch: "Passwords do not match.",
    success_title: "Success",
    success_password_changed: "Password changed successfully!",
    reset_password_title: "Reset Password",
    paste_private_key: "Paste your Private Key",
    continue_button: "Continue",
    error_invalid_private_key: "Invalid private key.",
    error_private_key_mismatch: "The private key does not match the current wallet.",
    define_new_password: "Set New Password",
    reset_button: "Reset",
    success_password_reset: "Password reset successfully!",
    create_wallet_description: "Create a strong password to secure your wallet",
    enter_password: "Enter your password",
    confirm_password: "Confirm your password",
    password_criteria_hint: "Password must be at least 11 characters including uppercase, lowercase, numbers and special characters (!@#$%^&*).",
    wallet_created: "Wallet Created",
    wallet_address_label: "Address",
    error_create_wallet: "Failed to create wallet",
    enter_private_key: "Enter your private key",
    import_button: "Import",
    validation_empty_private_key: "Private key cannot be empty!",
    define_secure_password: "Set a Secure Password",
    encrypt_button: "Encrypt",
    wallet_imported: "Wallet Imported",
    wallet_imported_message: "Address:",
    attention_title: "⚠️ WARNING",
    reset_warning: "If you have not saved your private key, YOU WILL LOSE ALL ACCESS to your wallet!",
    reset_instruction: "Before resetting, make sure you saved your private key so you can recover your wallet in the future.",
    hold_instruction: "Press and hold the button below to reset.",
    hold_button_text: "Press and Hold",
    wallet_reset_title: "Wallet Reset!",
    wallet_reset_text: "All data has been erased. Reloading...",
    cancel_button: "Cancel",
    save_your_private_key: "SAVE YOUR PRIVATE KEY",
    private_key_alert_before_funding: "Before funding your wallet, save your private key."
  }
};

export default traducao;
